spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/umbrella?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: password
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20

  mybatis:
    configuration:
      multiple-result-sets-enabled: false
      map-underscore-to-camel-case: true
      call-setters-on-nulls: true
      jdbc-type-for-null: varchar
      default-fetch-size: 500

    properties:
      hibernate:
        show-sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB